logging:
  config: classpath:logback.xml
#mysql
mybatis:
  mapper-locations: classpath*:sqlmap/**/*.xml
  config-location: classpath:mybatis-Config.xml
spring:
  datasource:
    druid:
      username: root
      password: root
      #单数据源改为url
      url: jdbc:mysql://106.52.179.22:8020/mine?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2b8
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 200
      max-idle: 10
      min-idle: 8
      initial-size: 10
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.ico
        session-stat-enable: false
        session-stat-max-count: 10
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username:
        login-password:
        allow:
        deny:
      filter:
        stat:
          enabled: true
          db-type: h2
          log-slow-sql: true
server:
  #修改jsp文件不用重启
  jsp-servlet.init-parameters.development: true
  #指定端口号
  port: 8080
